# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: HOW ARE WE FREE
email: "lifelinesphilly@gmail.com"
author: 'LifeLines: Voices Against the Other Death Penalty'
description: > # this means to ignore newlines until "baseurl:"
  *How Are We Free* explores the nature of freedom and confinement through creative 
  collaboration between people who have been sentenced to die in prison and visual 
  artists outside the prison walls. Visual economies and regimes of power have been 
  massively employed by the state and the media in order to criminalize people. This 
  exhibit interrupts those regimes and instead invites viewers to investigate what 
  actually creates conditions for safety, healing, justice, transformation, and liberation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LifelinesPA
facebook_username: lifelinespa
instagram_username: lifelines_project
author_url: "http://lifelines-project.org/"
asset_subpath: "/hawf/"
# asset_subpath: ""

collections:
  works:
    output: true
    layout: collection-item
    permalink: /:collection/:name

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: works
    values:
      layout: collection-item

# Prose settings
prose:
  media: 'assets/images'

# Build settings
markdown: kramdown
theme: jekyll-theme-clean-blog
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "*.txt"
  - vendor/**
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - assets/fonts
  - assets/images
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"