# howarewefree.org config settings

# for serving locally, uncomment `asset_subpath` entry 

title: HOW ARE WE FREE
email: "lifelinesphilly@gmail.com"
author: 'LifeLines: Voices Against the Other Death Penalty'
description: > # this means to ignore newlines until "baseurl:"
  *How Are We Free* explores the nature of freedom and confinement through creative 
  collaboration between people who have been sentenced to die in prison and visual 
  artists outside the prison walls. Visual economies and regimes of power have been 
  massively employed by the state and the media in order to criminalize people. This 
  exhibit interrupts those regimes and instead invites viewers to investigate what 
  actually creates conditions for safety, healing, justice, transformation, and liberation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: LifelinesPA
facebook_username: lifelinespa
instagram_username: lifelines_project
author_url: "http://lifelines-project.org/"

# production
asset_subpath: "/h"
ga_id: UA-73782411-2 # google analytics id

# dev
# asset_subpath: ""
# ga_id: ""

collections:
  works:
    output: true
    layout: collection-item
    permalink: /:collection/:name
  responses:
    output: false
  interviews:
    output: false

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: works
    values:
      layout: collection-item

# Prose settings
prose:
  media: 'assets/images'
  rooturl: '_posts'
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          placeholder: "enter post title"
          help: This will appear as the post title
          label: "title"
      - name: "date"
        field:
          element: "text"
          help: Date of post affects in which order posts appear
          value: CURRENT_DATETIME
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          placeholder: "choose existing or add categories"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          help: "Check if you'd like to see this post published to the public site"
          value: false
    _works:
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "categories"
        field:
          element: "multiselect"
          label: "Categories"
          placeholder: "choose existing or add categories"
          alterable: true
          options:
            - name: 'freedom'
              value: 'freedom'
            - name: 'incarceration'
              value: 'incarceration'
            - name: 'portrait'
              value: 'portrait'
      - name: "contributors"
        -field:
          element: "select"
          label: "Contributors"
          alterable: false
          options:
            - name: "Phill and Kate"
              value: phill and kate
            - name: "Terri and Noelle"
              value: terri and noelle
            - name: "Charles and Makeba"
              value: charles and makeba
            - name: "Nkechi and Alma"
              value: nkechi and alma
            - name: "Dawud and Matice"
              value: dawud and matice
            - name: "Mechie and Robin"
              value: mechie and robin
      - name: "featured"
        field:
          element: "checkbox"
          label: "Featured"
          help: "Check if you'd like to see this post appear in the featured gallery"
          value: false
      - name: "featured_order"
        field:
          element: "text"
          label: "Featured Gallery Order"
          help: "Enter the numerical order in which works should appear"
      - name: "image"
        field:
          element: "text"
          label: "Image file"
          help: Filename for the image
      - name: "published"
        field:
          element: "checkbox"
          label: "Published"
          help: "Check if you'd like to see this post published to the public site"
          value: true


# Build settings
markdown: kramdown

kramdown:
  smart_quotes: lsquo,rsquo,ldquo,rdquo

theme: jekyll-theme-clean-blog
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - "*.txt"
  - "vendor/**"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  # - assets/fonts
  # - assets/images
keep_files:
  - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"